### PR TITLE
Feature ticket#407 telemetry file io

### PR DESCRIPTION
**Pull request by HaydenAuterhoff**
The Epic#407 ticket for Telemetry data file IO for JSON objects were created in FileHandler

### CODE REVIEW

**Review by talon-ernst — CHANGES_REQUESTED** [review]
The ReadTelemetryData method needs to return the deserialized data from the function so we can use it elsewhere. It is currently being put into a Telemetry object and is immediately lost upon exiting the function.

**Comment by HaydenAuterhoff** [comment]
The ReadTelemetryData method was updated to return deserialized JSON information. I had a misunderstanding about how the Telemetry class was handling the deserialized data.

**Comment by omarnunezsiri** [comment]
The `ReadTelemetryData` and `WriteTelemetryData` methods _should_ be properly unit tested before merging onto the dev branch. Will review as soon as changes are pushed.

**Review by omarnunezsiri — APPROVED** [review]
Hi @HaydenAuterhoff ,

I had the opportunity to test these changes myself on my machine, looks good to me! Good job 😄

**Pull request merged**
